### ISSUE TITLE
一个服务处理不同的请求　如何绑定在一起呀SearchServiceImpl :: Notify这里面吗？

### ISSUE THREAD

**Issue by aleafboat** [Tencent/phxrpc#24]
一个服务处理不同的请求　如何绑定在一起呀SearchServiceImpl :: Notify这里面吗？

**Comment by liusifan** [comment]
如果只是增加一个接口的话，在 proto 文件中增加接口，然后重新生成代码，在 serviceimpl 实现对应的接口就可以了。如果是增加一种服务的话，一般建议新增一个模块，而不是合并到一个已有的模块。

假设最初有一个Account模块，用于存储用户的帐号，最初有 AddUser，UpdateUser，Auth的接口，如果要加一个 DeleteUser 的接口，那么在 account.proto 文件新增就好了。但如果想保存地址本，那么建议新增一个Contact的模块，而不是把这个功能加到 Account 模块。
