### ISSUE TITLE
关于用protobuf定义接口以及通信数据结构的疑问

### ISSUE THREAD

**Issue by huzhongx** [Tencent/phxrpc#29]
这里我有个疑问，如果rpc接口返回的数据结构十分复杂，比如以前是http接口返回的是一个json字符串，这个json字符串很长，并且其中的某些字段内容经常变化。这时候改造成rpc接口，用pb来描述接口返回值的话，pb的定义会很复杂繁琐，并且pb的字段最好只增加不减少，针对这种场景，你们在实际使用过程中，有没有遇到，以及是如何处理的呢。

**Comment by liusifan** [comment]
如果觉得用pb来定义很复杂，那么生成json字符串的代码通常也不会简单；一般来说，用pb生成代码，创建出对象来操作，比起直接拼接json，会减少很多错误。

在pb中要增减字段，一般有两个层面的问题。第一个层面，是在解包、打包的过程，在pb 3.0之前的版本，只要选择把字段设置为 optional 就可以解决；在 3.0 中默认就是 optional 。第二个层面是代码中对字段的使用，在增加字段之后，本来就需要对应用层的代码作出修改，才能使用新字段，或者去掉对旧字段的使用。

因此使用 pb 并不会增加工作量，反而减轻了打包、解包的工作量，方便了应用层代码的编写。

**Comment by huzhongx** [comment]
感谢回复，从代码编写角度来看，使用pb确实比拼json字符串要方便。可能比较大的代价在于第一次改造json字符串为pb对象的工作量会比较大，不知道之前你们有类似的改造工作没。

**Comment by liusifan** [comment]
之前有类似的工作，是把 xml 转换为 pb 定义，再写了一个 pb2xml 的接口。这样不用直接拼写 xml，而是操作 pb 的对象，对象被填充值之后，使用 pb2xml 就可以生成 xml 。

把 xml 转换为 pb 定义的时候，的确是重复性手工拉动，不过也就是一次性的，忍一忍就过去了，:)

**Comment by huzhongx** [comment]
就是说为了兼容老的xml接口，虽然用了pb，但是为写一个pb2xml的接口对吧。

**Comment by unixliang** [comment]
> 感谢回复，从代码编写角度来看，使用pb确实比拼json字符串要方便。可能比较大的代价在于第一次改造json字符串为pb对象的工作量会比较大，不知道之前你们有类似的改造工作没。

protobuf @ e8ae137 从这个版本开始已经提供了json和pb之间的转换接口，不用自己写了。
