### ISSUE TITLE
sample下面的例子，启动的时候该怎么测试，Search函数 -q后面参数和Notify -m后面参数该写什么

### ISSUE THREAD

**Issue by meicool** [Tencent/phxrpc#30]
Search函数 -q后面参数和Notify -m后面参数该写什么

**Comment by lynncui00** [comment]
您好，sample只是代码编写的样例，里面的Search和Notify功能都并未实现，无实际含义。如果需要测试的话，可以用Echo.

**Comment by Takechiyoo** [comment]
您好，我执行./search_tool_main -f PhxEcho -s hello 一直返回-1 是不是需要在proto文件中增加一个phxecho的rpc？
