### ISSUE TITLE
每次rpc调用都要新开一个进程吗？

### ISSUE THREAD

**Issue by kp-ljquality** [Tencent/phxrpc#34]
每次rpc调用都要新开一个进程吗？如何想要自行调用函数的话，每个函数有个OptMap类型的参数，这个类的定义找不到。难道每次调用都要把参数传进main函数，然后再转化成某个函数调用？

**Comment by liusifan** [comment]
phxrpc的codegen工具有自动生成client的类，在需要调用的地方 include client的头文件，然后声明 client 类直接调用就好了。有 OptMap 的代码是 codegen 自动生成的测试工具代码，可以看成是使用 client 代码的一个示例。
