### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [Tencent/phxrpc#7]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html) in [the destructor for the class "OptMap"](https://github.com/tencent-wechat/phxrpc/blob/0db0fa2cc2c18fc9990f118c7523d6d75f332b7c/phxrpc/file/opt_map.cpp#L35).

**Comment by berockguo** [comment]
有必要这样刷github吗？

**Comment by taohex** [comment]
Double check `nullptr != opt_string_` before `free`.

**Comment by elfring** [comment]
[The function “free”](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") tolerates a passed null pointer. So there is no need for such “a double check”.
